-- V3__create_event_outbox.sql
CREATE TABLE event_outbox
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type   VARCHAR(255) NOT NULL,
    binding      VARCHAR(255) NOT NULL,
    message_key  VARCHAR(255),

    payload_json JSONB NOT NULL,
    headers_json JSONB,

    status       VARCHAR(32)  NOT NULL,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    sent_at      timestamptz  NOT NULL,
    attempts     INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX ix_event_outbox_status_created ON event_outbox (status, created_at);
