CREATE TABLE event_outbox (
                              id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              event_type    VARCHAR(100)  NOT NULL,
                              binding       VARCHAR(200)  NOT NULL,
                              message_key   VARCHAR(200),

                              payload_json  JSONB,
                              headers_json  JSONB,

                              status        VARCHAR(16)   NOT NULL,
                              created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
                              sent_at       TIMESTAMPTZ,
                              attempts      INTEGER       NOT NULL DEFAULT 0,

                              CONSTRAINT chk_event_outbox_status
                                  CHECK (status IN ('PENDING','SENT','FAILED'))
);

CREATE INDEX ix_event_outbox_status_created
    ON event_outbox (status, created_at);

