services:
  eureka:
    build:
      context: ../../
      dockerfile: eureka-server/Dockerfile
    container_name: eureka
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8761/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  zipkin:
    image: openzipkin/zipkin:2.24
    container_name: zipkin
    ports:
      - "9411:9411"
    # prosto: bez healthchecka (Zipkin jest lekki i szybki)

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus:ro
    ports:
      - "9090:9090"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: starports
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d starports"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"               # tylko HOST listener wystawiamy na zewnątrz
    environment:
      # KRaft (bez Zookeepera)
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094

      # === LISTENERS ===
      # Broker nasłuchuje na 3 gniazdach:
      # - PLAINTEXT_HOST: dla klientów z hosta (IntelliJ) -> localhost:9092
      # - PLAINTEXT_DOCKER: dla kontenerów w sieci Compose -> kafka:9093
      # - CONTROLLER: KRaft quorum
      KAFKA_LISTENERS: PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT_DOCKER://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094

      # To, co broker ogłasza klientom (metadata):
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT_DOCKER://kafka:9093

      # Mapowanie nazw listenerów na protokoły
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT

      # Komunikacja między brokerami (tu single-node) po „dockerowym” listenerze
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER

      # Pozostałe sensowne domyślne
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      kafka:
        condition: service_started

#  starport-registry:
#    build:
#      context: ../../
#      dockerfile: starport-registry/Dockerfile
#    container_name: starport-registry
#    depends_on:
#      eureka:
#        condition: service_healthy
#      postgres:
#        condition: service_healthy
#      zipkin:
#        condition: service_started
#      kafka:
#        condition: service_started
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "8080:8080"
