spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/starports
    username: postgres
    password: postgres

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
