global:
    scrape_interval: 3s
    evaluation_interval: 3s

#scrape_configs:
#    - job_name: 'prometheus'
#      static_configs:
#          - targets: ['host.docker.internal:9090']

#    - job_name: 'apps'
#      metrics_path: '/actuator/prometheus'
#      static_configs:
#        - targets: ['host.docker.internal:7654','host.docker.internal:6543']
scrape_configs:
  - job_name: "starport-registry"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081", "host.docker.internal:8084"]

  - job_name: "trade-route-planner"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8082", "host.docker.internal:8083"]

  - job_name: "telemetry-pipeline"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8090", "host.docker.internal:8091"]

  - job_name: "loki"
    metrics_path: /metrics
    static_configs:
      - targets: [ "host.docker.internal:3100" ]   # lub 'loki:3100' jeśli w tej samej sieci dockerowej
